name: "Build ESP32-S3 (unsigned)"
on:
  workflow_dispatch:

jobs:
  build-esp32:
    name: Build ESP32-S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: 'recursive'
          persist-credentials: false

      - name: Build ESP32
        run: |
          ./workflows/autobuild.sh esp32

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: pico-fido-esp32
          path: release/*
          if-no-files-found: warn
